FROM node:10-alpine
WORKDIR /src
ARG SERVICE
ENV NODE_ENV=development
COPY services/$SERVICE/package.json ./services/$SERVICE/package.json
COPY services/$SERVICE/package-lock.json ./services/$SERVICE/package-lock.json
RUN npm install --prefix services/$SERVICE
COPY common ./services/$SERVICE/common
COPY services/$SERVICE/ ./services/$SERVICE/
WORKDIR /src/services/$SERVICE
CMD [ "npm", "run" ,"start:dev" ]
EXPOSE 3000
EXPOSE 50050