FROM node:10
WORKDIR /src
ARG SERVICE
ENV NODE_ENV=development
COPY services/$SERVICE/package.json ./services/$SERVICE/package.json
COPY services/$SERVICE/package-lock.json ./services/$SERVICE/package-lock.json
RUN npm install --prefix services/$SERVICE
WORKDIR /src/services/$SERVICE
EXPOSE 4000
CMD [ "npm", "run" ,"start" ]